# Generated by Django 3.2.8 on 2021-10-23 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='address',
            field=models.CharField(max_length=2540),
        ),
        migrations.AlterField(
            model_name='crew',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 22, 7, 35, 4, 170721, tzinfo=utc)),
        ),
    ]
