# Generated by Django 3.2.8 on 2021-10-23 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20211023_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charter',
            name='from_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 22, 8, 36, 4, 483231, tzinfo=utc)),
        ),
    ]
